### ISSUE TITLE
Deleting user via admin page fails

### ISSUE THREAD

**Issue by marc-sturm** [PavlidisLab/rgr#130] opened 2021-11-09 08:42 UTC
Hi Guillaume,

deleting users fails again, similar to #114 .

Here the user I wanted to delete:
![2021-11-09 09_35_17-Admin - Rare Diseases_ Models   Mechanisms Network Europe](https://user-images.githubusercontent.com/5638144/140891067-a2e4ec10-afc6-4e84-b280-d9cc09e4a954.png)

And here the error message:
![2021-11-09 09_35_28-Mozilla Firefox](https://user-images.githubusercontent.com/5638144/140891121-3b2bd7fe-4fe5-46df-9602-e615512e24f2.png)

I hope this is enough information to reproduce the error.

Best,
  Marc

**Comment by arteymix** [comment] 2021-11-09 17:42
The issue in #114 was caused by a broken delete cascade on associated tokens. It does not appear to be the problem here.

It seems that a unique constraint is violated. I recall we had a problem regarding user emails, but that has already been addressed in the v1.4.3. @marc-sturm Could you check if another user has the same email in your database?

**Comment by marc-sturm** [comment] 2021-11-09 19:38
There is no duplicate email, but the name is registered three times with different email adresses. Maybe that causes a problem.

**Comment by arteymix** [comment] 2021-11-09 20:23
Can you grab the stacktrace from the logs?

**Comment by marc-sturm** [comment] 2021-11-10 06:55
You can find the log here:
https://download.imgag.de/ahsturm1/rdp.log

**Comment by arteymix** [comment] 2021-11-10 16:09
I just figured it out, and I also understand why I had to remove the non-null constraint on the token's user: the tokens were deleted individually prior to deleting the user, bypassing Hibernate's cascading mechanism.

I'll revert the fix from #114 and do the right thing: simply delete the user and let Hibernate take care of its tokens.

**Comment by arteymix** [comment] 2021-11-10 16:10
This is caused by a user having more than one password or verification token.

**Closed** 2021-11-10 17:48 UTC
Labels: bug
